CREATE CURSOS:BASE​
TRUNCATE CURSOS:BASE 1024
WRITE CURSOS:BASE 0 SISTEMAS_OPERATIVOS
FLUSH CURSOS:BASE
COMMIT CURSOS:BASE
READ CURSOS:BASE 0 8​
TAG CURSOS:BASE CURSOS:V2
DELETE CURSOS:BASE
WRITE CURSOS:V2 0 SISTEMAS_OPERATIVOS_2
COMMIT CURSOS:V2
END